server:
  port: 8080

spring:
  application:
    name: policia-judiciaria-civil
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/policia_judiciaria_civil_db
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
